// Thin wrapper around the OpenNext-generated worker so we can re-export custom
// Durable Object classes. Wrangler bundles this file (referenced via `main` in
// wrangler.toml) and imports the OpenNext default fetch handler.

// @ts-expect-error - generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

export { StatsAggregator } from "./src/lib/stats-aggregator";

type OpenNextHandler = {
  fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> | Response;
};

const openNextHandler = handler as OpenNextHandler;

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    return openNextHandler.fetch(request, env, ctx);
  },
};
