// Thin wrapper around the OpenNext-generated worker so we can re-export our
// custom Durable Object classes. Wrangler bundles this file (referenced via
// `main` in wrangler.toml), it imports the OpenNext default fetch handler,
// routes PartyServer websocket traffic first, and re-exports DO classes so
// their `class_name` bindings in wrangler.toml resolve.

// @ts-expect-error - generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";
import { routePartykitRequest } from "partyserver";

export { LunarLanderParty } from "./src/lib/labs/lunar-lander-party-room";
export { StatsAggregator } from "./src/lib/stats-aggregator";

type OpenNextHandler = {
  fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> | Response;
};

const openNextHandler = handler as OpenNextHandler;

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const partyResponse = await routePartykitRequest(request, env);
    if (partyResponse) return partyResponse;

    return openNextHandler.fetch(request, env, ctx);
  },
};
