// Thin wrapper around the OpenNext-generated worker so we can re-export our
// custom Durable Object class (StatsAggregator). Wrangler bundles this file
// (referenced via `main` in wrangler.toml), it imports the OpenNext default
// fetch handler, and re-exports both the handler and the DO class so the
// `class_name = "StatsAggregator"` binding in wrangler.toml resolves.

// @ts-expect-error - generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

export { StatsAggregator } from "./src/lib/stats-aggregator";
export default handler;
