name: Build & Deploy to Github Pages

# See https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_HOST: cdn.contentful.com
          CONTENTFUL_DOWNLOAD_LOCAL: false
